# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('workflow_id', models.CharField(max_length=200)),
                ('inputs', django_mysql.models.JSONField(default=dict)),
                ('fixed_inputs', django_mysql.models.JSONField(default=dict, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In Active')], default='A', max_length=10)),
            ],
        ),
    ]
