# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1', max_length=20)),
                ('workflow_id', models.CharField(max_length=200)),
                ('inputs', models.CharField(blank=True, max_length=400, null=True)),
                ('fixed_inputs', models.CharField(blank=True, max_length=400, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In Active')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('type_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In Active')], default='A', max_length=10)),
            ],
            managers=[
                ('workflows', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workflows',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.WorkflowType'),
        ),
    ]
