# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workflowtype',
            managers=[
                ('wf_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workflowtype',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
