# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20160926_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorkFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.CharField(default=b'2016-10-07 12:08:32', max_length=50)),
                ('update_date', models.CharField(default=b'2016-10-07 12:08:32', max_length=50)),
                ('type', models.CharField(max_length=100, null=True)),
                ('samples_list', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabWorkFlowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('status_name', models.CharField(default='new lab work created', max_length=50)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labworkflows',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.LabWorkFlowStatus'),
        ),
    ]
