# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20161007_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labworkflows',
            name='created_date',
            field=models.CharField(default=b'2016-10-13 15:01:37', max_length=50),
        ),
        migrations.AlterField(
            model_name='labworkflows',
            name='update_date',
            field=models.CharField(default=b'2016-10-13 15:01:37', max_length=50),
        ),
    ]
