# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
