# Generated by Django 3.0.8 on 2023-01-14 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='contents',
        ),
        migrations.AddField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ContentTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fail', models.BooleanField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Content')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(help_text='null=main category', null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Category')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='content_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Category'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(through='info.ContentTags', to='info.Tags'),
        ),
    ]
