# Generated by Django 3.0.8 on 2023-10-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20230113_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
