# Generated by Django 3.0.8 on 2023-10-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20231022_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
