# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20160706_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='거래처',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('코드', models.IntegerField()),
            ],
        ),
    ]
