# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_거래처'),
    ]

    operations = [
        migrations.AddField(
            model_name='거래처',
            name='거래처명',
            field=models.CharField(default='--', max_length=200),
            preserve_default=False,
        ),
    ]
