# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_거래처_거래처명'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='번호',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='거래처',
            name='코드',
            field=models.CharField(max_length=200),
        ),
    ]
