# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_auto_20160706_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='출하',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.CharField(max_length=200)),
                ('예정량', models.IntegerField()),
                ('거래처', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.거래처')),
            ],
        ),
        migrations.CreateModel(
            name='현장',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('현장명', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='출하',
            name='현장',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.현장'),
        ),
    ]
