# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_auto_20160707_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='거래처',
            name='email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='대표자',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='연락처1',
            field=models.CharField(default='000-0000-0000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='연락처2',
            field=models.CharField(default='fax', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='연락처3',
            field=models.CharField(default='담당자', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='주소',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='거래처',
            name='현장',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='shipment.현장'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='출하',
            name='사각',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='출하',
            name='차량',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
