# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_auto_20160710_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='거래처',
            name='현장',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.현장'),
        ),
        migrations.AlterField(
            model_name='거래처',
            name='코드',
            field=models.CharField(default='0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='출하',
            name='거래처',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.거래처'),
        ),
        migrations.AlterField(
            model_name='출하',
            name='현장',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.현장'),
        ),
        migrations.AlterField(
            model_name='현장',
            name='현장명',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
