# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_auto_20160711_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='수주',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.CharField(max_length=200)),
                ('일자', models.DateField(default=datetime.date.today)),
                ('원청', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.거래처')),
                ('현장', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.현장')),
            ],
            options={
                'ordering': ['번호'],
            },
        ),
    ]
