# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_auto_20160714_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='규격',
            name='규격명',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
