# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_규격_규격명'),
    ]

    operations = [
        migrations.CreateModel(
            name='규격명',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m40', models.CharField(default='40mm', max_length=200)),
                ('m25', models.CharField(default='25mm', max_length=200)),
                ('m19', models.CharField(default='19mm', max_length=200)),
                ('m13', models.CharField(default='13mm', max_length=200)),
            ],
        ),
    ]
