# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0015_auto_20160715_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='규격명',
            new_name='standard_name',
        ),
    ]
