# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0016_auto_20160715_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard_name',
            old_name='석분',
            new_name='sd',
        ),
    ]
