# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0020_auto_20160716_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='car',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='standard',
        ),
    ]
