# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0021_auto_20160716_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='contracts',
        ),
    ]
