# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0023_auto_20160716_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='site',
        ),
        migrations.AddField(
            model_name='customers',
            name='site',
            field=models.ManyToManyField(default=0, to='shipment.sites'),
        ),
    ]
