# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0026_auto_20160717_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='sites',
        ),
        migrations.AddField(
            model_name='sites',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipment.customers'),
        ),
    ]
