# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0027_auto_20160717_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='standard',
        ),
        migrations.AddField(
            model_name='sites',
            name='standards',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
